// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/mjmhtjain/enpal/src/internal/domain"
	dto "github.com/mjmhtjain/enpal/src/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// AppointmentService is an autogenerated mock type for the IAppointmentService type
type AppointmentService struct {
	mock.Mock
}

// FindFreeSlots provides a mock function with given fields: _a0
func (_m *AppointmentService) FindFreeSlots(_a0 domain.CalendarQueryDomain) ([]dto.CalendarQueryResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for FindFreeSlots")
	}

	var r0 []dto.CalendarQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CalendarQueryDomain) ([]dto.CalendarQueryResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.CalendarQueryDomain) []dto.CalendarQueryResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CalendarQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CalendarQueryDomain) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppointmentService creates a new instance of AppointmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppointmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppointmentService {
	mock := &AppointmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
